1. 
 - numpy의 행렬을 사용하여 다음 연립 방정식의 푸는 프로그램을 작성하세요
   X0,X1,X2의 값을 구하세요 구한 값이 맞는지 np.dot()함수로 확인해보세요

In [26]:
# 3*X0 + 2*X1 - 4*X2 = 52 
# 2*X0 - 4*X1 + 9*X2 = -27
# 5*X0 + 3*X1 - 7*X2 = 86
import numpy as np
A = np.mat("3 2 -4; 2 -4 9; 5 3 -7")
print(A)
b = np.array([52,-27,86])
x = np.linalg.solve(A,b) # A * x를 곱했을 때 b가 만드는거
print(x)   #[10.  5. -3.]

#2  
print(np.dot(A,x))   #[[ 52. -27.  86.]]  = b 





[[ 3  2 -4]
 [ 2 -4  9]
 [ 5  3 -7]]
[10.  5. -3.]
[[ 52. -27.  86.]]


2.
   - numpy의 dot() 함수와 같은 기능을 하는 mydot() 함수를 구현하세요
     numpy의 dot()함수를 사용하지 않고 for문을 사용하여 구현하고
     실행 결과를 np.dot()함수로 실행한 출력 결과와 비교해보세요
     (numpy의 dot()함수이외의 인덱싱,슬라이싱,sum()과 같은 함수는 사용해도 무방)

In [24]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)
a.dot(b)
b.shape[0]

3

2. numpy의 dot() 함수와 같은 기능을 하는 mydot() 함수를 구현하세요
   numpy의 dot()함수를 사용하지 않고 for문을 사용하여 구현하고
   실행 결과를 np.dot()함수로 실행한 출력 결과와 비교해보세요
   (numpy의 dot()함수이외의 인덱싱,슬라이싱,sum()과 같은 함수는 사용해도 무방)

In [30]:
# shape의 데이터 타입은 튜플임

def mydot(a,b):
    r = np.arange(a.shape[0]*b.shape[1]).reshape(a.shape[0],
                                                 b.shape[1])
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c = a[i, :] * b[:, j]
            r[i][j]= c.sum()
    return r
# (m,n) * (n,l) = (m,l)

a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)
print('\na.dot(b):')
print(a.dot(b))
print('\nmydot(a,b):')
print(mydot(a,b))

# [[10 13]
#  [28 40]]

a = np.arange(24).reshape(4,6)
b = np.arange(54).reshape(6,9)
print('\n a.dot(b):')
print(a.dot(b))
print('\n mydot(a,b):')
print(mydot(a,b))


a.dot(b):
[[10 13]
 [28 40]]

mydot(a,b):
[[10 13]
 [28 40]]

 a.dot(b):
[[ 495  510  525  540  555  570  585  600  615]
 [1305 1356 1407 1458 1509 1560 1611 1662 1713]
 [2115 2202 2289 2376 2463 2550 2637 2724 2811]
 [2925 3048 3171 3294 3417 3540 3663 3786 3909]]

 mydot(a,b):
[[ 495  510  525  540  555  570  585  600  615]
 [1305 1356 1407 1458 1509 1560 1611 1662 1713]
 [2115 2202 2289 2376 2463 2550 2637 2724 2811]
 [2925 3048 3171 3294 3417 3540 3663 3786 3909]]
