# 02장 Numpy  기본 

In [2]:
# 라이브러리 설치 : pip install numpy
import numpy as np
data1 = [0,1,2,3,4,5]
print(type(data1))        # <class 'list'>
a1 = np.array(data1)
print(type(a1))          # <class 'numpy.ndarray'>
a1 
# ndarray : 다차원 지원

<class 'list'>
<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5])

In [9]:
a1.dtype  # 인스턴스멤버 data2 = [0,1,2,3.1,4.1]

dtype('int32')

In [10]:
data2 = [1,2,3.2,4.5,5.0]
a2 = np.array(data2)
print(a2)
print(type(a2))
print(a2.dtype)
a2

[1.  2.  3.2 4.5 5. ]
<class 'numpy.ndarray'>
float64


array([1. , 2. , 3.2, 4.5, 5. ])

In [11]:
# np.arange()
a3 = np.arange(12)
print(a3)
a3

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a4 = np.arange(2,10)
a4

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a5 = np.arange(0,16,2)
a5

array([ 0,  2,  4,  6,  8, 10, 12, 14])

2차원, 3차원, 다차원

In [3]:
m = np.array([np.arange(3), np.arange(3)])
print(m)
print(m.shape)
m  
#[[0 1 2]   #같은  arange를 했을때 이렇게 나옴
# [0 1 2]]

d = np.array([np.arange(3), np.arange(4)])
print(d) # [array([0, 1, 2]) array([0, 1, 2, 3])]  왜 이렇게? 2차원아닌강..?**************************************************8

[[0 1 2]
 [0 1 2]]
(2, 3)
[array([0, 1, 2]) array([0, 1, 2, 3])]


In [15]:
m2 = np.arange(12)
print(m2)
print(m2.shape)
m2

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
m3 = np.arange(12).reshape(2,2,3)
print(m3)
print(m3.shape)
m3
print(m3[1,1,2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
11


In [17]:
m_list = [[[[1,2,3],[4,5,6]]]]
m = np.array(m_list)
print(m3.shape)    #괄호가 4개 -> 4차원!
m

(2, 2, 3)


array([[[[1, 2, 3],
         [4, 5, 6]]]])

2차원, 3차원, 다차원
rank : 차원, 첫 데이터까지의 대괄호의 갯수
shape: 차원의 요소들의 수
        1차원 shape : (x, )
        2차원 shape : (x,y)
        3차원 shape : (x,y,z)
        ...
        n차원 shape : (x,y,z, ...)
       

배열의 shpae 바꾸기 : reshape()

In [18]:
d = np.arange(12)  # 1차원
print(d.shape)
print(d)
d = d.reshape(3,4)  #2차원
print(d.shape)
print(d)

d = d.reshape(2,3,2)  # 3차원
print(d.shape)
print(d)

d = d.reshape(1,2,3,2)  # 4차원
print(d.shape)
print(d)

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(1, 2, 3, 2)
[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]]


In [19]:
d = np.arange(12)   # 1차원
print(d.shape)
print(d)
d = d.reshape(3,4)  #2차원
print(d.shape)
print(d)

d = d.reshape(-1,6)  # 행의  요소수를 자동으로 계산 
print(d.shape)
print(d)

d = d.reshape(4,-1)  # 열의 요소수를 자동으로 계산 
print(d.shape)
print(d)

(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


배열의 인덱싱과 슬라이싱

In [20]:
# 1차원 배열의 인덱싱과 슬라이싱: list와 동일한 방법
d = np.arange(12)
print(d)
print(d[0],d[1],d[2],d[-1])
print(d[:-1],d[::3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0 1 2 11
[ 0  1  2  3  4  5  6  7  8  9 10] [0 3 6 9]


In [21]:
# 2차원 배열의 인덱싱과 슬라이싱 
# date[행,열]
d = np.arange(12).reshape(3,4)
print(d)
# 인덱싱
print(d[0,0])
print(d[2,2])   # 10
#슬라이싱
print(d[0])    #[ 0  1  2  3]
print(d[0,:])  #[ 0  1  2  3]
print(d[::])   
print(d[::2,::2])
d[0] = 20
print(d)
d[::3,::3] = 30
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
10
[0 1 2 3]
[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 8 10]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[30 20 20 30]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
# 3차원 배열의 인덱싱과 슬라이싱 
# date[행,열,면]
d = np.arange(12).reshape(2,2,3)
print(d)
# 인덱싱
print(d[1,0,1])  # 7
print(d[0,1,2])  #5
print()
# 슬라이싱
print(d[:,:-1,:-1])    #shape:(2,1,2)
print()
print(d[:,1:,1:]) 
# [[[4 5]]            #shape:(2,1,2)
#  [[10 11]]]


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
7
5

[[[0 1]]

 [[6 7]]]

[[[ 4  5]]

 [[10 11]]]


In [23]:
d = np.arange(12).reshape(3,4)  #2차원
print(d)
print(d[0])
# [0 1 2 3]

print(d[0][1])  # 먼저 1차원으로 추출하고 거기서 2차원 추출 
# 1

print(d[0,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
1
1


In [24]:
d = np.arange(12).reshape(2,2,3)    #3차원

print(d)
# print(d[0])
# print(d[0][1][0])  # 3
print(d[0,1,0])    # 3

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


배열 형상 다루기: 편평화(flatten), 전치(transpose), reshape

In [25]:
# flatten  # 다차원 배열을 1차원으로 만든다
d = np.arange(12).reshape(3,4)
print(d)
# f = d.flatten()   #[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
f = d.reshape(12,)     # *******************************************************이친구는 무엇인가요....
print(f,f.shape)   #(12,)
f = f.reshape(3,4)   
print(d)

# 데이터를 거꾸로 변형 
print(d[::-1])  # 행의 순서를 거꾸로 변경 
print(d[:,::-1]) # 열의 순서를 거꾸로 변경 
print(d[::-1,::-1]) # 행과 열의 순서를 거꾸로 변경 

# transpose(): 전치 행렬, 행과 열을 서로 맞바꾸는 함수
t = d.transpose()
print(t)   #(4,3)
# [[ 0  4  8]
#  [ 1  5  9]
#  [ 2  6 10]
#  [ 3  7 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


배열합치기
- 수평(h, 열)으로 합치기 : hstack(), column_Stack(), axis = 1
- 수직(v, 행)으로 합치기 : vstack(), row_stack(), axis = 0

In [26]:
# 수평으로 합치기 : hstack()
a = np.arange(9).reshape(3,3)
b = a *2 # 배열의 연산
print(a)
print(b)
r = np.hstack((a,b))
print(r)
c = np.column_stack((a,b))
print(c)

x = np.concatenate((a,b),axis = 1)  # 열 : axis = 1
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [27]:
# 수직으로 합치기 : vstack()
a = np.arange(9).reshape(3,3)
b = a *2 # 배열의 연산
print(a)
print(b)
r = np.vstack((a,b))
print(r)
c = np.row_stack((a,b))
print(c)

x = np.concatenate((a,b),axis = 0)  # 행 : axis = 0
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


쪼개기
- hsplit(배열, 열의 갯수) : 수평, 열 , axis = 1
- vsplit(배열, 행의 갯수) : 수직, 행  , axis = 0

In [28]:
a = np.arange(12).reshape(3,4)
print(a)

print(np.hsplit(a,4))
print(np.split(a,4,axis = 1))

print(np.vsplit(a,3))
print(np.split(a,3,axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


Numpy 속성(Attrribute): 클래스의 인스턴스 멤버변수
    - T, flat, ndim, nbytes, size, dtype

In [29]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.nbytes)    #48: byte 단위로 데이터 크기
print(a.size)     #12 : 데이터 크기
print(a.dtype)    # int32 -> 4 byte
print(a.ndim)     # 2 : 차원의 크기
print(a.T)        # 전치 행렬
a.flat = 0        # 배열 전체를 0으로 변경 
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
48
12
int32
2
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


배열의 뷰(View)와 사본(Copy)
- View : 원본 객체와 메모리를 공유한다
- copy : 원본 객체와는 다른 별도의 메모리를 사용한다

In [30]:
import scipy.misc
import matplotlib.pyplot as plt

face = scipy.misc.face()    #read only 읽기 전용!
face2 = face.copy()   #face2: read and write 가능 
print(type(face2))    
print(face2.shape)    #(768, 1024, 3)print(a.nbytes)    #48: byte 단위로 데이터 크기
print(face2.nbytes)   # 2359296  48: byte 단위로 데이터 크기
print(face2.size)     # 2359296 : 데이터 크기
print(face2.dtype)    # int8 -> 4 byte
print(face2.ndim)     # 3 : 차원의 크기

f_copy = face2.copy()
f_copy.flat = 0
f_view = face2.view()
# f_view.flat = 0 
# face2[:,:,1] = 0
plt.subplot(221)
plt.imshow(face2)
# face2[:,:,1] = 0
# for i in range(768):
#     for j in range(1024):
#         for k in range(3):
#             face[i][j][k] = 0

plt.subplot(222)
plt.imshow(f_copy)

plt.subplot(223)
plt.imshow(f_view)
plt.show()


# print(face2)

<class 'numpy.ndarray'>
(768, 1024, 3)
2359296
2359296
uint8
3


<Figure size 640x480 with 3 Axes>

4장 행렬과 선형 회귀대수

In [48]:
import numpy as np

a = np.arange(12).reshape(3,4)
# int(mp.zero(10))

# numpy의 통계함수
print(a.sum())
print(a.mean())
print(a.std())
print(a.max())
print(a.min())

from scipy.stats import scoreatpercentile
print(scoreatpercentile(a,50))
print(np.median(a))

66
5.5
3.452052529534663
11
0
5.5
5.5


In [49]:
# 행렬과 선형대수
A = np.mat("2 4 6 8 ;4 2 6 8 ;10 -4 18 8")
print(type(A),A)
print(A)
#역행렬 : A * X = E(항등행렬, 왼쪽 위에서 대각선으로 1이고 나머지는 0)

<class 'numpy.matrix'> [[ 2  4  6  8]
 [ 4  2  6  8]
 [10 -4 18  8]]
[[ 2  4  6  8]
 [ 4  2  6  8]
 [10 -4 18  8]]


In [55]:
#역행렬
inverse = np.linalg.inv(A)
print(inverse)

print(A*inverse)
#[[1 0 0 
#  0 1 0 
#  0 0 1]]

[[29.  11.5  7. ]
 [16.   6.5  4. ]
 [ 4.   1.5  1. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
# 선형(linear)방정식
A = np.mat("1 -2 1; 0 2 -8; -4 5 9") #메트릭스 행렬
print(A)
b = np.array([0,8,-9])
print(b)
# 1*X0 - 2*X1 + 1*X2 = 0.
# 0*X0 +2*X1 - 8*X2 = 8
#-4*X0 + 5*X1 + 9*X2 = -9  #우리는 미지수를 구하는게 목적이아니라 기울기 구하는게 중요!
x = np.linalg.solve(A,b) #답은 b에 있당
print('using solve:',x,x.shape) 
print(np.dot(A,x))  #A * X = b   --> WxX = Y
#                     x = inverse_A * b 
inverse = np.linalg.inv(A)
x = np.dot(inverse,b)
print(x)
print('using inverse:',x)


[[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
[ 0  8 -9]
using solve: [29. 16.  3.] (3,)
[[ 0.  8. -9.]]
[[29. 16.  3.]]
using inverse: [[29. 16.  3.]]


In [54]:
a1 = np.arange(4).reshape(2,2)
a2 = np.arange(4).reshape(2,2)
print(a1)
print(a2)
print(a1 * a2) # element-wise 곱셈 :요소간의 곱셈
print(np.dot(a1,a2)) #matrix 곱셈, product 곱셈
# (m,n) * (n*l) = (m*l)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]
